version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - appNetwork
    dns:
      - 8.8.8.8
    command: yarn dev --host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    networks:
      - appNetwork
    dns:
      - 8.8.8.8
    command: yarn start:dev

networks:
  appNetwork:
    driver: bridge
